pokeapi/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('pokemon.urls')),

]

pokemon/urls.py
"""Defines URL patterns for pokemon"""

from django.urls import path

from .import views

app_name = "pokemon"

urlpatterns = [
    path('', views.index, name='index'),
    path('pokemons/<name>', views.my_pokemons, name='my_pokemons'),
    path('pokemons/delete/<name>', views.delete_pokemons, name='delete_pokemons'),
    path('user-profile/', views.profile, name='profile'),
    path('user-info/', views.users_info, name='users_info'),
    path('pokemons/<username>/', views.user_pokemons, name='user_pokemons'),

    # api urls
    path('api/', views.api_overview, name='api_overview'),
    path('api/users/', views.users_api, name='users_api'),
    path('api/pokemons/<username>/', views.user_pokemons_api, name='user_pokemons_api'),

]

users/urls.py
from django.urls import path, include

from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
    path('login_check/', views.login_check, name='login_check'),
]

pokemon/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User


class Pokemon(models.Model):
    name = models.CharField(max_length=200, unique=True)
    image_url = models.URLField(max_length=2000)
    api_url = models.URLField(max_length=2000)
    types = ArrayField(models.CharField(max_length=200), blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    owners = models.ManyToManyField(User, related_name='owners')

    def __str__(self):
        return self.name

users/models.py
from django.db import models

# Create your models here.

pokemon/views.py
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
import requests
from django.contrib.auth.models import User
from django.db.utils import IntegrityError
from rest_framework.decorators import api_view
from rest_framework.response import Response
from rest_framework import status

from .serializers import PokemonSerializer, UserSerializer
from .models import Pokemon


def index(request):
    response = requests.get("http://pokeapi.co/api/v2/pokemon?limit=50").json()
    pokemons = response['results']

    if request.user.is_authenticated:
        user_pokemons = Pokemon.objects.filter(owners=request.user).order_by('id')
        user_pokemon_names = [p.name for p in user_pokemons]
        header = "Choose Your Pokemons"
    else:
        user_pokemon_names = []
        header = "To be able to choose pokemons, please Log in"

    context = {'pokemons': pokemons, 'names': user_pokemon_names, 'header': header}
    return render(request, 'pokemon/index.html', context)

def my_pokemons(request, name):
    pokemon_url = ""
    response = requests.get("http://pokeapi.co/api/v2/pokemon?limit=50").json()
    pokemons = response['results']

    for pokemon in pokemons:
        if pokemon['name'] == name:
            pokemon_url = pokemon['url']
            pokemon['in_db'] = "yes"

    pokemon_data = requests.get(pokemon_url).json()
    pokemon_name = pokemon_data['name']
    pokemon_img = pokemon_data['sprites']['front_default']
    pokemon_types = [t['type']['name'] for t in pokemon_data['types'] if pokemon_data['types']]

    new_pokemon = Pokemon(
        name=pokemon_name,
        image_url=pokemon_img,
        api_url=pokemon_url,
        types=pokemon_types,
    )
    try:
        new_pokemon.save()
        new_pokemon.owners.add(request.user)
    except IntegrityError:
        this_pokemon = Pokemon.objects.get(name=name)
        this_pokemon.owners.add(request.user)

    return redirect('pokemon:index')


def delete_pokemons(request, name):
    pokemon = Pokemon.objects.get(name=name)
    pokemon.owners.remove(request.user)

    return redirect('pokemon:index')


def profile(request):
    my_pokemons = Pokemon.objects.filter(owners=request.user).order_by('id')
    content = {'my_pokemons': my_pokemons}
    return render(request, 'pokemon/profile.html', content)


def users_info(request):
    users = User.objects.all()
    context = {'users': users}
    return render(request, 'pokemon/users_info.html', context)


def user_pokemons(request, username):
    the_user = User.objects.get(username=username)
    pokemons = Pokemon.objects.filter(owners=the_user)
    context = {'pokemons': pokemons, 'the_user': the_user}
    return render(request, 'pokemon/user_pokemons.html', context)


# api functions
@api_view(["GET"])
def api_overview(request):
    api_urls = {
        'Users List': 'api/users/',
        'User Pokemons': 'api/pokemons/{username}/',
    }
    return Response(api_urls)


@api_view(['GET'])
def users_api(request):
    users = User.objects.all()
    serializer = UserSerializer(users, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def user_pokemons_api(request, username):
    try:
        user = User.objects.get(username=username)
    except ObjectDoesNotExist:
        context = {'not found': f'user with username {username} does not exist'}
        return Response(context, status=status.HTTP_404_NOT_FOUND)
    pokemons = Pokemon.objects.filter(owners=user)
    serializer = PokemonSerializer(pokemons, many=True)
    return Response(serializer.data)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import messages
from django.contrib.auth.models import User


def register(request):
    """Register a new user"""
    if request.method == "POST":
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('pokemon:index')
    else:
        form = UserCreationForm()

    context = {'form': form}

    return render(request, 'registration/register.html', context)


def login_check(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        check_username = request.POST['username']

        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect("pokemon:index")
        else:
            if User.objects.filter(username=check_username).exists():
                messages.error(request, "Invalid password.")
                return redirect("users:login_check")
            else:
                messages.error(request, "No such user. Please check the username"
                                        " or register if you haven't registered yet")
                return redirect("users:login_check")
    else:
        form = AuthenticationForm()

    context = {"form": form}

    return render(request, "registration/login.html", context)





pokemon/templates/pokemon/base.html
{% load bootstrap5 %}
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial=scale=1, shrink-to-fit=no">
    <link rel=”stylesheet” href=”https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css” />

    <title>PokeApiTest</title>

  {% bootstrap_css %}
  {% bootstrap_javascript %}
  {% bootstrap_messages %}

</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

    <a class="navbar-brand" href="{% url 'pokemon:index' %}">POKEAPI</a>

    <div class="collapse navbar-collapse" id="navbarCollapse">
    <ul class="navbar-nav ms-auto">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'pokemon:users_info' %}">All Users</a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:register' %}">Register</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:login_check' %}">Log in</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'pokemon:profile' %}">{{ user.username }}</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
        </li>

        {% endif %}
      </ul>
    </div>
  </nav>

  <main role="main" class="container">
    <div class="pb-2 border-bottom">
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>

  </main>

</body>

</html>

pokemon/templates/pokemon/home.html
{% extends "pokemon/base.html" %}

{% block page_header %}

<div>
  <h3>Hello</h3>
</div>

{% endblock %}

{% block content %}

{% endblock content %}

pokemon/templates/pokemon/index.html
{% extends "pokemon/base.html" %}

{% block page_header %}

<div>
  <h3>{{ header }}</h3>
</div>

{% endblock %}

{% block content %}

{% for pokemon in pokemons %}

<div>
  <h4>{{ pokemon.name }}</h4>
  {% if user.is_authenticated %}
  {% if pokemon.name not in names %}
  <a class="btn btn-outline-success" href="{% url 'pokemon:my_pokemons' pokemon.name %}">Add to My Pokemons</a>
  {% else %}
  <a class="btn btn-outline-danger" href="{% url 'pokemon:delete_pokemons' pokemon.name %}">Delete from My Pokemons</a>
  {% endif %}
  {% endif %}
</div>

{% endfor %}

{% endblock content %}

pokemon/templates/pokemon/profile.html
{% extends "pokemon/base.html" %}

{% block page_header %}

<div>
  <h3>{{ user.username }} Profile</h3>
</div>

{% endblock %}

{% block content %}
<h4>My Pokemons </h4>
{% for pokemon in my_pokemons %}
<ul>
  <li><h4>{{ pokemon.name }}</h4></li>
  <img src="{{ pokemon.image_url }}">
  <a class="btn btn-outline-success" href="">CHOOSE</a>
  <p>{{ pokemon.types }}</p>
</ul>
{% endfor %}
{% endblock content %}

pokemon/templates/pokemon/user_pokemons.html
{% extends "pokemon/base.html" %}

{% block page_header %}

<div>
  <h3>{{ the_user.username }} Pokemons</h3>
</div>

{% endblock %}

{% block content %}
{% for pokemon in pokemons %}
<ul>
<li>
<h4>{{ pokemon.name }}<h4>
</li>
</ul>
{% endfor %}
{% endblock content %}

pokemon/templates/pokemon/users_info.html
{% extends "pokemon/base.html" %}

{% block page_header %}

<div>
  <h3>All Users</h3>
</div>

{% endblock %}

{% block content %}
{% for user in users %}
<ul>
  <li>
  <h4>{{ user.username }}</h4>
  <a href="{% url 'pokemon:user_pokemons' user %}">Show Pokemons List</a>
  </li>
</ul>
{% endfor %}
{% endblock content %}